# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summery',
            field=models.TextField(error_messages={'required': 'summery needed'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(error_messages={'required': 'text needed'}),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', error_messages={'required': 'title needed'}, max_length=100),
        ),
    ]
