# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20170712_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='offset',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
