# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20170712_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='offset',
        ),
    ]
