# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20170712_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name="blog's name"),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name="post's title"),
        ),
    ]
