# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_blog_posts_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posts_words',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
