# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'required': 'username needed'}, max_length=20, unique=True)),
                ('first_name', models.CharField(error_messages={'required': 'first name needed'}, max_length=100)),
                ('last_name', models.CharField(error_messages={'required': 'last name needed'}, max_length=100)),
                ('email', models.EmailField(error_messages={'required': 'email needed'}, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=64)),
                ('expiry', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
